title: &title ANH Dispatch Reports
subtitle: &subtitle ANH Dispatch Reports ETL Pipeline
description: &description |
  This project contains the ETL pipeline for the ANH Dispatch Reports dataset.

keywords: &keywords
  - anh
  - dispatch
  - reports
  - bolivia

author: Andres Chirinos
created_date: 2025-06-15
version: 1.0.0

data_dir: data
output_dir: output

github_repo:
  owner: andreschirinos
  name: p2p-bob-exchange
  description: *description

github_actions:
  artifact:
    logs:
      retention_days: 14
    data:
      retention_days: 14

drive:
  #target:
  #credentials: "drive_credentials.json"
  folder_id: "1gk3zVIZzPVP3tm3jMPY_RiSrfVOwdscR"
  #name: "my-awesome-dataset"
  #child_folder: "data"
  #owner: "timoboz"

kaggle:
  title: *title
  subtitle: *subtitle
  description: *description
  id: ""
  #id_no: 12345
  licenses:
    - name: "CC0-1.0"
  resources:
    - path: "advertiser.parquet"
      description: "Advertiser data from the BOB exchange"
      schema:
        fields:
          - name: "advertiser_userno"
            order: 0
            description: "Unique identifier for the advertiser"
            type: "string"
          - name: "advertiser_nickname"
            order: 1
            description: "Nickname of the advertiser"
            type: "string"
          - name: "advertiser_monthordercount"
            order: 2
            description: "Number of orders placed by the advertiser in the last month"
            type: "number"
          - name: "advertiser_monthfinishrate"
            order: 3
            description: "Finish rate of the advertiser in the last month"
            type: "number"
          - name: "advertiser_positiverate"
            order: 4
            description: "Positive rate of the advertiser"
            type: "number"
          - name: "advertiser_usertype"
            order: 5
            description: "Type of the advertiser (e.g., user, merchant)"
            type: "string"
          - name: "advertiser_usergrade"
            order: 6
            description: "Grade of the advertiser"
            type: "string"
          - name: "advertiser_u seridentity"
            order: 7
            description: "Identity of the advertiser (e.g., MASS_MERCHANT, BLOCK_MERCHANT)"
            type: "string"
          - name: "advertiser_viplevel"
            order: 8
            description: "VIP level of the advertiser"
            type: "number"
          - name: "advertiser_isblocked"
            order: 9
            description: "Indicates if the advertiser is blocked"
            type: "boolean"
          - name: "advertiser_activetimeinsecond"
            order: 10
            description: "Active time of the advertiser in seconds"
            type: "number"
          - name: "timestamp"
            order: 11
            description: "Timestamp of the data collection"
            type: "datetime"
          - name: "source"
            order: 12
            description: "Source of the data (e.g, binance)"
            type: "string"
      name: advertiser
      profile: tabular-data-resource
      title: Advertiser Table
      format: format
      encoding: utf-8
    - path: "advice.parquet"
      description: "Advice data"
      name: advice
    - path: "trade_methods.parquet"
      description: "Trade methods data"
      name: trade_methods
  keywords: *keywords
  name: "p2p-bob-exchange"
  homepage: "https://sociest.org"
  version: "1.0.0"
  contributors:
    - "title": "Andres Chirinos"
      "role": "author"
  licenses:
    - name: "CC0-1.0"
      title: "CC0 1.0"
      path: "https://creativecommons.org/publicdomain/zero/1.0/"