title: &title ANH Dispatch Reports
subtitle: &subtitle ANH Dispatch Reports ETL Pipeline
description: &description |
  This project contains the ETL pipeline for the ANH Dispatch Reports dataset.

keywords: &keywords
  - anh
  - dispatch
  - reports
  - bolivia

author: Andres Chirinos
created_date: 2025-06-15
version: 1.0.0

data_dir: data
output_dir: output

github_repo:
  owner: andreschirinos
  name: p2p-bob-exchange
  description: *description

github_actions:
  artifact:
    logs:
      retention_days: 14
    data:
      retention_days: 14

drive:
  #target:
  #credentials: "drive_credentials.json"
  folder_id: "1gk3zVIZzPVP3tm3jMPY_RiSrfVOwdscR"
  #name: "my-awesome-dataset"
  #child_folder: "data"
  #owner: "timoboz"

kaggle:
  title: *title
  subtitle: *subtitle
  description: *description
  id: "andreschirinos/anh-dispatch-report"
  #id_no: 12345
  licenses:
    - name: "CC0-1.0"
  resources:
    - path: "dispatches.csv"
      description: "Dispatches data"
      schema:
        fields:
          - name: "destino"
            order: 0
            description: "Destination of the dispatch"
            type: "string"
          - name: "localidad"
            order: 1
            description: "Locality of the dispatch"
            type: "string"
          - name: "producto"
            order: 2
            description: "Product of the dispatch"
            type: "string"
          - name: "hora_salida"
            order: 3
            description: "Departure time of the dispatch"
            type: "datetime"
          - name: "hora_llegada_aprox"
            order: 4
            description: "Approximate arrival time of the dispatch"
            type: "datetime"
          - name: "source"
            order: 5
            description: "Source of the data"
            type: "string"
          - name: "timestamp"
            order: 6
            description: "Timestamp of the data collection"
            type: "datetime"
      name: dispatches
      profile: tabular-data-resource
      title: "Dispatches Data"
      format: csv
      encoding: utf-8
  keywords: *keywords
  name: "anh-dispatch-report"
  version: "1.0.0"
  contributors:
    - "title": "Andres Chirinos"
      "role": "author"
  licenses:
    - name: "CC0-1.0"
      title: "CC0 1.0"
      path: "https://creativecommons.org/publicdomain/zero/1.0/"